# Generated by Django 3.2.9 on 2022-03-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_topics_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='schools',
        ),
    ]
