# Generated by Django 3.2.9 on 2022-03-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220301_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
